-- Run explicitly with npm run db:migrate or paste the entire file in SQL Editor.
-- This schema is server-only: do NOT add vitarecall to the exposed API schemas.
BEGIN;
SELECT pg_advisory_xact_lock(1987346112);
CREATE SCHEMA IF NOT EXISTS vitarecall;
REVOKE ALL ON SCHEMA vitarecall FROM PUBLIC;

CREATE TABLE IF NOT EXISTS vitarecall.schema_migrations (
  version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS vitarecall.users (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK (role IN ('patient','clinician')),
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS vitarecall.sessions (
  token_hash TEXT PRIMARY KEY, user_id TEXT REFERENCES vitarecall.users(id),
  csrf_token TEXT NOT NULL, expires_at BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS vitarecall.demo_profiles (
  user_id TEXT PRIMARY KEY REFERENCES vitarecall.users(id), username TEXT NOT NULL,
  recovery_hash TEXT UNIQUE NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS vitarecall.patients (
  id TEXT PRIMARY KEY, user_id TEXT UNIQUE NOT NULL REFERENCES vitarecall.users(id),
  care_code TEXT UNIQUE NOT NULL, memory_consent INTEGER NOT NULL DEFAULT 0 CHECK (memory_consent IN (0,1)),
  consent_updated_at TEXT
);
CREATE TABLE IF NOT EXISTS vitarecall.care_team (
  patient_id TEXT NOT NULL REFERENCES vitarecall.patients(id),
  clinician_id TEXT NOT NULL REFERENCES vitarecall.users(id), created_at TEXT NOT NULL,
  PRIMARY KEY (patient_id,clinician_id)
);
CREATE TABLE IF NOT EXISTS vitarecall.messages (
  rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES vitarecall.patients(id),
  user_id TEXT NOT NULL REFERENCES vitarecall.users(id), role TEXT NOT NULL,
  text TEXT NOT NULL, sources_json TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS messages_scope ON vitarecall.messages(patient_id,user_id,rowid);
CREATE TABLE IF NOT EXISTS vitarecall.chat_conversations (
  patient_id TEXT NOT NULL REFERENCES vitarecall.patients(id),
  user_id TEXT NOT NULL REFERENCES vitarecall.users(id), cutoff_sequence BIGINT NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL, PRIMARY KEY (patient_id,user_id)
);
CREATE TABLE IF NOT EXISTS vitarecall.message_memory_traces (
  message_id TEXT PRIMARY KEY REFERENCES vitarecall.messages(id), trace_json TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS vitarecall.chat_requests (
  patient_id TEXT NOT NULL, user_id TEXT NOT NULL, request_id TEXT NOT NULL,
  state TEXT NOT NULL, response_json TEXT, created_at TEXT NOT NULL,
  PRIMARY KEY (patient_id,user_id,request_id)
);
CREATE TABLE IF NOT EXISTS vitarecall.memories (
  id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES vitarecall.patients(id),
  user_id TEXT NOT NULL REFERENCES vitarecall.users(id), request_id TEXT NOT NULL,
  text TEXT NOT NULL, provenance TEXT NOT NULL, status TEXT NOT NULL,
  job_id TEXT, blob_id TEXT, owner TEXT, namespace TEXT NOT NULL, error TEXT,
  created_at TEXT NOT NULL, UNIQUE (patient_id,user_id,request_id)
);
CREATE TABLE IF NOT EXISTS vitarecall.notes (
  id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES vitarecall.patients(id),
  user_id TEXT NOT NULL REFERENCES vitarecall.users(id), text TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS vitarecall.tasks (
  id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES vitarecall.patients(id),
  user_id TEXT NOT NULL REFERENCES vitarecall.users(id), title TEXT NOT NULL,
  completed INTEGER NOT NULL DEFAULT 0 CHECK (completed IN (0,1)), created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS vitarecall.audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT, patient_id TEXT, action TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS vitarecall.rate_limits (
  key TEXT PRIMARY KEY, count INTEGER NOT NULL, until BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS vitarecall.operation_locks (
  key TEXT PRIMARY KEY, token TEXT NOT NULL, expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_expiry ON vitarecall.sessions(expires_at);
CREATE INDEX IF NOT EXISTS memories_patient ON vitarecall.memories(patient_id,created_at);

-- Defense in depth: even an accidentally exposed schema cannot be read by API roles.
REVOKE ALL ON ALL TABLES IN SCHEMA vitarecall FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA vitarecall FROM PUBLIC;
DO $permissions$
DECLARE api_role TEXT; app_table TEXT;
BEGIN
  FOREACH api_role IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=api_role) THEN
      EXECUTE format('REVOKE ALL ON SCHEMA vitarecall FROM %I', api_role);
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA vitarecall FROM %I', api_role);
      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA vitarecall FROM %I', api_role);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA vitarecall REVOKE ALL ON TABLES FROM %I', api_role);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA vitarecall REVOKE ALL ON SEQUENCES FROM %I', api_role);
    END IF;
  END LOOP;
  FOR app_table IN SELECT tablename FROM pg_tables WHERE schemaname='vitarecall' LOOP
    EXECUTE format('ALTER TABLE vitarecall.%I ENABLE ROW LEVEL SECURITY', app_table);
  END LOOP;
END
$permissions$;
INSERT INTO vitarecall.schema_migrations(version) VALUES ('001_initial') ON CONFLICT (version) DO NOTHING;
COMMIT;
